import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/image";
import { parseEther, formatEther, Contract, BrowserProvider } from "ethers";
import { useState, useEffect } from "react";

import Navbar from "@/components/Navbar";
import TipCard from "@/components/TipCard";

import buyMeACoffeeAbi from "../constants/BuyMeACoffee.json";
import buyMeACoffeeAddresses from "../constants/networkMapping.json";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [tips, setTips] = useState([]);
  const [tipMessage, setTipMessage] = useState("");

  useEffect(() => {
    fetchTips();
  }, []);

  const buyCoffee = async (amount, message) => {
    const browserProvider = new BrowserProvider(window.ethereum);
    const signer = await browserProvider.getSigner();
    const network = await browserProvider.getNetwork();
    console.log(network.chainId.toString());

    console.log(buyMeACoffeeAddresses[network.chainId.toString()][0]);

    const buyMeACoffeeContract = new Contract(
      buyMeACoffeeAddresses[network.chainId.toString()][0],
      buyMeACoffeeAbi.fragments,
      signer
    );

    const tx = await buyMeACoffeeContract.buyCoffee(message, {
      value: parseEther(amount.toString()),
    });
  };

  const fetchTips = async () => {
    const browserProvider = new BrowserProvider(window.ethereum);
    const network = await browserProvider.getNetwork();
    const buyMeACoffeeContract = new Contract(
      buyMeACoffeeAddresses[network.chainId.toString()][0],
      buyMeACoffeeAbi.fragments,
      browserProvider
    );

    const fethchedTips = await buyMeACoffeeContract.getLatestFiveTips();
    const tipsArr = fethchedTips
      .map((tip) => {
        return { tip: formatEther(tip[0]), message: tip[1] };
      })
      .filter((element) => {
        return element.tip != "0.0";
      });
    setTips(tipsArr);

    // fethchedTips
    //   .filter((tip) => {
    //     return tip[0] != 0n; //removes blank elements from array
    //   })
    //   .map((tip) => {
    //     setTips((prev) => [
    //       ...prev,
    //       {
    //         tip: formatEther(tip[0]),
    //         message: tip[1],
    //       },
    //     ]);
    //   });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
        <div className="w-full flex justify-center">
          <div className="flex flex-col w-[70%] items-center justify-center mt-20 bg-slate-100 p-10 rounded-md">
            <div className="flex">
              <div className="flex-1 flex items-center justify-center">
                <div className="rounded-xl object-contain overflow-hidden">
                  <Image
                    src="/coffee.jpg"
                    alt="coffee"
                    width="400"
                    height="400"
                  />
                </div>
              </div>

              <div className="flex flex-1 flex-col items-center justify-center gap-5">
                <button
                  className="w-[200px] bg-cyan-600 rounded-full text-white font-bold p-2 hover:bg-cyan-500"
                  onClick={() => buyCoffee("0.0001", tipMessage)}
                >
                  5 eur
                </button>
                <button
                  className="w-[200px] bg-cyan-600 rounded-full text-white font-bold p-2 hover:bg-cyan-500"
                  onClick={() => buyCoffee("0.0005", tipMessage)}
                >
                  10 eur
                </button>
                <button
                  className="w-[200px] bg-cyan-600 rounded-full text-white font-bold p-2 hover:bg-cyan-500"
                  onClick={() => buyCoffee("0.001", tipMessage)}
                >
                  15 eur
                </button>
              </div>

              <textarea
                placeholder="Type tip message here"
                value={tipMessage}
                onChange={(e) => setTipMessage(e.target.value)}
                className="p-3"
              ></textarea>
            </div>

            <div className="flex flex-wrap gap-5 mt-20 w-full justify-center">
              {tips.map((tip, index) => (
                <TipCard tip={tip} key={index} />
              ))}
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
